### ISSUE TITLE
Trying to change the language causes problems.

### ISSUE THREAD

**Issue by hwahyang1** [outloudvi/info-pride#106] opened 2024-03-03 11:36 UTC
It seems to only happen on pages that don't have translation applied. (ex - [/notemap](https://ip.outv.im/ko/notemap))

**Comment by outloudvi** [comment] 2024-03-03 16:27
Thanks for reporting! This should have the same root cause as #103, and both should have been fixed by now.

**Closed** 2024-03-03 16:27 UTC
Labels: bug
